# Generated by Django 5.2.12 on 2026-03-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('vida_min', models.IntegerField()),
                ('vida_max', models.IntegerField()),
                ('hipoalergenico', models.BooleanField(default=False)),
            ],
        ),
    ]
